# Generated by Django 5.0.6 on 2024-07-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remainder',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток'),
        ),
    ]
