# Generated by Django 5.0.6 on 2024-07-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_product_remainder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remainder',
            field=models.PositiveIntegerField(verbose_name='Остаток'),
        ),
    ]
